public class GoogleBooksAccessInfo {
    public String country { get; set; }
    public String viewability { get; set; }
    public Boolean embeddable { get; set; }
    public Boolean publicDomain { get; set; }
    public String textToSpeechPermission { get; set; }
    public GoogleBooksEpub epub { get; set; }
    public GoogleBooksPdf pdf { get; set; }
    public String webReaderLink { get; set; }
    public String accessViewStatus { get; set; }
}